# Generated by Django 4.2.9 on 2024-01-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('IdBranche', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=20)),
                ('Localisation', models.CharField(max_length=30, null=True)),
                ('Etat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('IdEmploye', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('Nationalite', models.CharField(max_length=15, null=True)),
                ('CarteIdentite', models.CharField(max_length=20, null=True)),
                ('Phone', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('Etat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('Nom', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Heures', models.CharField(max_length=30)),
                ('Interval', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('IdService', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NomService', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('NumeroTicket', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NomClient', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('Plaque', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Marque', models.CharField(max_length=20, null=True)),
                ('Place', models.IntegerField()),
                ('Etat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heure', models.CharField(max_length=15, verbose_name='Heure')),
                ('DateDepart', models.DateTimeField(verbose_name='Date de départ')),
                ('IdEmploye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employe')),
                ('NomLigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ligne')),
                ('NumeroTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ticket')),
            ],
            options={
                'unique_together': {('NumeroTicket', 'NomLigne', 'IdEmploye')},
            },
        ),
        migrations.CreateModel(
            name='Travaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Annee', models.IntegerField()),
                ('IdBranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.branche')),
                ('IdEmploye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employe')),
                ('IdService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.service')),
            ],
            options={
                'unique_together': {('IdEmploye', 'IdBranche', 'IdService', 'Date')},
            },
        ),
        migrations.CreateModel(
            name='Conduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Heure', models.CharField(max_length=15)),
                ('IdEmploye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employe')),
                ('NomLigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ligne')),
                ('Plaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.vehicules')),
            ],
            options={
                'unique_together': {('IdEmploye', 'Plaque', 'NomLigne', 'Date')},
            },
        ),
    ]
