# Generated by Django 4.2.9 on 2024-01-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGuichetView',
            fields=[
                ('IdEmploye', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('Nationalite', models.CharField(max_length=15, null=True)),
                ('CarteIdentite', models.CharField(max_length=20, null=True)),
                ('Phone', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('Etat', models.CharField(max_length=20)),
                ('ZoneResponsabilite', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChauffeurView',
            fields=[
                ('IdEmploye', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('Nationalite', models.CharField(max_length=15, null=True)),
                ('CarteIdentite', models.CharField(max_length=20, null=True)),
                ('Phone', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('Etat', models.CharField(max_length=20)),
                ('Licence', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEmploye',
            fields=[
                ('AuditId', models.AutoField(primary_key=True, serialize=False)),
                ('IdEmploye', models.CharField(max_length=10)),
                ('AncienEtat', models.CharField(max_length=20)),
                ('NouvelEtat', models.CharField(max_length=20)),
                ('DateHeureModification', models.DateTimeField()),
            ],
        ),
    ]
